/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32_uart.h"

#define LOCAL_BUFFER_SIZE	100

int main(void)
{
	/* Set Clock (CLK) for peripherals */
	if (STM_OK != enableClock())
	{
		/* Loop forever if HSE cannot be set as MCU CLK */
		for(;;);
	}

	/* Enable peripherals */
	configPeripheralClock();

	/* Configure GPIO C pin 10 (TX) and 11 (RX) */
	configGPIO4UART();

	/**
	 * Configure UART peripherals:
	 * 	BD = 115200 bits/s
	 * 	Stop bits = 1
	 * 	Parity = None
	 */
	configUART4();

	/* data to be send */
	/* (warning: TX (pin10) = RX from TTL to USB device */
	char *p = "Hello with larger WORDDD my P!\r\n";
	char r_p[LOCAL_BUFFER_SIZE] = {0};
	uint32_t idx;

	UART_writeBurst(p);

	while (1)
	{
		if (UART_RX_FRAME == UART_read(r_p))
		{
			UART_writeBurst(r_p);
			idx = 0;
			while(idx < LOCAL_BUFFER_SIZE)
			{
				r_p[idx++] = '\0';
			}
		}
	}
    /* Loop forever */
	for(;;);
}
